### ISSUE TITLE
Question: Best approach to implementing a timestamp with nanosecond precision and timezone awareness

### ISSUE THREAD

**Issue by emwalker** [matsadler/magnus#113]
We have a situation where we'd like to pass a Ruby `Time` instance to Rust and back, and we'd like to preserve nanosecond precision and awareness of the timezone (UTC in our case).  It seems that Magnus's support for timestamps does not include these two things.

I started looking into implementing `magnus::TryConvert` for a newtype that wraps `chrono::DateTime<Utc>`, but I see that `magnus::error::protect` and `magnus::Value::as_rb_value` are private, suggesting I'm approaching this problem in the wrong way.

What is the recommended way to add a type like this to a crate using Magnus?

**Comment by matsadler** [comment]
The public versions of `protect`  and `as_rb_value` are in the [`rb_sys` module](https://docs.rs/magnus/0.7.1/magnus/rb_sys/index.html) (as `magnus::rb_sys::protect` and `magnus::rb_sys::AsRawValue::as_raw`) and require enabling the `rb-sys` feature. They're hidden behind a feature because you should only need to use `protect` when interfacing with Ruby C api  directly with `rb-sys`, and converting to/from raw `VALUE` lets you break all sorts of rules.

I'm not sure why I didn't implement nanosecond precision, the APIs are all there. I'll give it a go and see if I encounter any problems.

I'd welcome a PR for conversion to/from `chrono::DateTime`, with that and the dependency on Chrono behind a feature, like [`RString::to_bytes`](https://docs.rs/magnus/0.7.1/magnus/r_string/struct.RString.html#method.to_bytes) needs the `bytes` feature enabled to bring in the dependency on the `bytes` crate.

**Comment by emwalker** [comment]
Many thanks for the helpful answer.  We're consulting on the best approach to use here.  The PR is a tempting idea.  Currently we have a Ruby wrapper around our own Rust struct using `magnus::wrap(...)`, and that is working at a basic level but is a little unergonomic on the Ruby side.  There's a good chance we'll come back to this at some point and maybe try the `TryConvert` implementation.

**Comment by matsadler** [comment]
I implemented nanosecond precision, you can give it a try by setting your Magnus dependency like:

``` toml
magnus = { git = "https://github.com/matsadler/magnus.git", rev = "4109aec" }
```
