### ISSUE TITLE
Is there a way to cheaply convert a `Vec<u8>` into an `RString`?

### ISSUE THREAD

**Issue by cstyles** [matsadler/magnus#122]
I see that there's a [`Ruby::str_from_slice`](https://docs.rs/magnus/0.7.1/magnus/struct.Ruby.html#method.str_from_slice) method that creates a new `RString` from a shared slice by copying the bytes into a new buffer. But if I have an owned buffer (`Vec<u8>`, `Box<[u8]>`, etc.), is there a way to just hand over the memory to Ruby and say "here, this is yours now"? Sort of like [`String::from_utf8`](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8) but for `RString` and without UTF-8 validation.

**Comment by matsadler** [comment]
Ruby doesn't really have a C API for this, so there's nothing for Magnus to bind to. Ruby does make the `RString` struct public, so it is possible to get access to the internal pointer, and even change it to point to some other memory. However, exposing this safely in Magnus would be pretty much impossible.

Ruby's embedded and shared strings make it tricky, but the biggest hurdle is that Ruby itself and a Rust extension could be using different allocators. Then if a Rust extension hands over a buffer to Ruby it would be allocated with Rust's allocator, but freed with Ruby's, which is not safe. And there's no way to verify Ruby and Rust are using the same allocator.

Magnus' [`RString`](https://docs.rs/magnus/latest/magnus/r_string/struct.RString.html) does implement the [`Write`](https://docs.rs/magnus/latest/magnus/r_string/struct.RString.html#impl-Write-for-RString) trait, so if whatever api you're working with gives the option to pass a buffer, you may be able to create a Ruby string with say [`Ruby::str_buf_new`](https://docs.rs/magnus/latest/magnus/struct.Ruby.html#method.str_buf_new), then write your data directly to it, rather than allocating an intermediary `Vec<u8>`.

**Comment by cstyles** [comment]
Yeah, I was afraid of that. The `Write` idea is interesting though; I'll see if it's feasible. Thanks for taking the time to explain!
