### ISSUE TITLE
How does Magnus, Rutie, uniffi-rs differ

### ISSUE THREAD

**Issue by schorsch** [matsadler/magnus#19]
I am on the search for tools to replace some ruby code with rust. (after mangling around with an external golang based service and all the mess those micro-service-approaches bring up)
So i came across different how-tos like [writing rust gem from scratch](https://briankung.dev/2022/02/02/writing-a-rust-gem-from-scratch/), [how to use rust with ruby](https://vericred.github.io/2020/02/19/how-to-use-rust-with-ruby.html) and i am bit puzzled about which way to go, also since i am learning rust along the way.

I understand that one should not pass arbitrary ruby objects into the rust-black box, but instead keep the interface small and clean. Besides the memory problems that can arise, this also to reduces the amount of translation-methods. With those, comes my question are there any advantages of using one or the other lib? They all seem to abstract the C-level wrapping. 
After taking a dive into uniffi-rs and generating one of their [examples](https://github.com/mozilla/uniffi-rs/tree/main/examples/todolist), their approach to build ruby code based on [templates](https://github.com/mozilla/uniffi-rs/tree/main/uniffi_bindgen/src/bindings/ruby/templates) and a general udf description seems pretty slick.

In the second mentioned article above the author talks about running rust outside of the ruby gvl, how does magnus deal with such?

I hope my questions are not to dummy, but there are quite some moving parts to figure out. A general info about the pros & cons of each approach could really help.

**Comment by matsadler** [comment]
Hey, sorry for taking so long to get back to you on this.

---

There’s two core ways to get Rust and Ruby talking to each other.

1. Use Rust’s ability to call C functions to call Ruby’s C API
2. Use Rust’s ability to export functions with a C ABI to allow Ruby (via the Ruby FFI gem) to call Rust

With the first you get to use all the features of Ruby, objects; classes; calling methods; etc. It’s just a bit clunky because you’re using those features from a foreign language.

The second you can only use the C ABI, so functions, pointers, ints, floats, and C-style strings. You’d then probably want to write a bunch of Ruby code to wrap those functions in a more Rubyesque API.

The straightforward approach to the first would be to directly use the Ruby C API via the `rb-sys` crate. This is what the “Writing a Rust gem from scratch” post does. This can end up being quite a lot of work, Ruby’s C API was designed for C, so it’s a bit of a chore to use from Rust and gives you plenty of ways to shoot yourself in the foot.

Both Rutie and Magnus take the first approach to the next level, wrapping the raw C API in Rust concepts, making it easier to use, and harder to make mistakes.

My massively bias opinion is that the way Magnus does this is nicer than Rutie, the biggest benefit being the automatic type conversions Magnus does for you, so you can write methods with Rust types and errors and have Magnus do all the conversions to Ruby objects and exceptions. The other bit difference is where things can go wrong Magnus makes it very clear to you that there is the possibility of failure, whereas Rutie is happier to assume the happy path. This makes Magnus a little harder to use in some places (but also makes it easier to spot mistakes earlier).

I’ve not seen it before, but from a quick skim, it looks like `uniffi-rs` is taking the second of our two core approaches, but automating writing a lot of the wrapping Ruby code for you. This looks like a nice approach when you also want to generate binding for other languages too.

My concerns with the `uniffi-rs` would be, FFI performance generally doesn’t match Ruby’s C api, particularly doing lots of smaller calls. So I’d want to check that makes sense for my use case. The other worry would be how well their generic udf format matches my use case. How much of Ruby’s feature set does it map to? What parts of that feature set do I want to use?

---

Currently Magnus doesn’t expose any functions to release the Ruby global variable lock. This feature of Ruby’s C api is very very hard to use correctly, so it needs a lot of careful design to expose it in Magnus and be able to give the kind of “if it compiles it works” guarantees that Rust developers are used to. This is on the roadmap.

**Comment by schorsch** [comment]
Thanks a lot for taking your time for this explanation! Maybe it could reside somewhere more visible, e.g. within an FAQ section of the readme.
Your concerns about uniffi-rs where also the things I thought about when reading the code.
