### ISSUE TITLE
Is there a way to not statically link under windows?

### ISSUE THREAD

**Issue by ms-jpq** [matsadler/magnus#2]
https://github.com/matsadler/magnus/blob/7684472c38722323b22589587f0c0d6136dacb82/build.rs#L36

Hey there, 

I am trying to just get one of the ruby <-> rust crates working under windows and it really doesn't look like its possible?

I was wondering if you had also bashed your face against the wall too on this haha.

My use case is building a gem that would compile everything ahead of time, and it seems to work all all platforms except windows, which is a big pain in my bum rn.

btw, very nice code! 👍

**Comment by matsadler** [comment]
Hi!

Working with Windows and pre-compiled gems on Windows are definitely things I want to support.

Windows should work, but I don't actually have a Windows machine, so I'm just relying on tests running under GitHub Actions.
I've not put a huge amount of time into pre-compiled gems yet (and I've not looked at pre-compiled gems on Windows at all), so things there might be a bit rough around the edges.

The line you've highlighted I added just a few days ago while [trying to get tests for an example gem working](https://github.com/matsadler/magnus/commit/42cbb03205e0d889942c359df5ac3ab736fcf94d) and hasn't make its way into a release yet. So if you're using the release version it shouldn't be a problem.

If you're using Magnus as a git dependency you could try the commit before that change:
```
magnus = { git = "https://github.com/matsadler/magnus.git", rev = "9b4f700" }
```

If you're using the release version it might be worth trying the main branch from GitHub, as it's possible that change might fix things.

I don't know what you're using to do the build, I have an [example `Rakefile`](https://github.com/matsadler/magnus/blob/7684472c38722323b22589587f0c0d6136dacb82/examples/rust_blank/ext/rust_blank/Rakefile) in this repo, or there's the recently [merged (but not yet released) cargo builder](https://github.com/rubygems/rubygems/pull/5175) for RubyGems, or the [rb_sys gem](https://github.com/oxidize-rb/rb-sys/tree/main/gem), but they all try to do the same thing. That is, take the compiler/linker flags Ruby would normally provide to a C compiler and adapt them for Rust, and then invoke the Rust compiler.

I think the rb_sys gem is the most robust of those options at the moment, and works with [rake-compiler](https://github.com/rake-compiler/rake-compiler) for precompiled gems. I've given it a quick test and it should work with an extension written with Magnus.

It'd be worth checking you're using the most up-to-dave version of whichever, I made changes to the linked `Rakefile` recently, the RubyGems cargo builder has updates in https://github.com/rubygems/rubygems/pull/5459, and the rb_sys gem had a 0.1.1 release a couple of days ago.

I'm a long way from an expert, but my understanding is that the `-Wl,-undefined,dynamic_lookup` flag is used on unix-like systems to tell the linker to not complain about missing symbols because come runtime Ruby will have already loaded them all before loading the extension. Ruby will usually pass this flag to C extensions, and any of the options mentioned above should as well.

As far as I can tell there is no equivalent for Windows, so you always need to provide some linker args or you'll get errors about not being able to find the library or unknown symbols. The code under the line you highlighted _should_ dynamically link Ruby, not statically. It is possible that if you're Ruby was compiled without the `--enable-shared` option then it would statically link. In that case you'd need to recompile Ruby with `--enable-shared`.

In my limited testing with dynamic linking (on macOS), before I got the `-Wl,-undefined,dynamic_lookup` flag figured out, I did see problems where while dynamically linked the version of Ruby you're running the extension with needed to exactly match the version compiled against (when normally you'd only match the minor version). I'm not sure if the same would happen on Windows, from what I've read Windows and unix implement linking very differently so it's hard to take learnings from one platform and apply them to the other.

I know @ianks has been working on pre-compiled gems, I think he has an example at https://github.com/ianks/rb-rust-gem so that might prove useful.

Hopefully some of that rambling might prove useful to you.

If you can share any details of how you're doing things, your code, or any error messages I might be able to help some more.

Please let me know if you manage to get things working and how, and then I can make sure future versions of Magnus make this easier for others.

**Comment by ianks** [comment]
Hey @ms-jpq, I've gotten things working properly for mingw* on windows in [this example](https://github.com/oxidize-rb/rb-sys/tree/main/examples/rust_reverse). MSVC support I haven't been able to get working yet, although it should be possible at some point. Happy to chat more if you need help.

**Comment by matsadler** [comment]
Hey, I'm going to close this now.

If you've found anything interesting you can share, or you still need help please feel free to reopen the issue.
