### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ankane** [matsadler/magnus#34]
Hey @matsadler, congrats on the 0.4 release!

I just created [Polars](https://github.com/ankane/polars-ruby) and moved [Tokenizers](https://github.com/ankane/tokenizers-ruby) to it and really enjoyed using it.

My Rust isn’t great, so I’m not sure what’s possible, but a few ideas:

1. Support for `&mut self` / mutability in classes without having [lots of borrows](https://github.com/ankane/polars-ruby/blob/master/ext/polars/src/series.rs)
2. Support for `MyClass` and `Vec<MyClass>` as method parameters - currently needs to be `&MyClass` (and `Vec<&MyClass>` not supported)
3. Support for `iter()` method on `RArray`

Thanks for creating this!

**Comment by matsadler** [comment]
> Hey @matsadler, congrats on the 0.4 release!
> 
> I just created [Polars](https://github.com/ankane/polars-ruby) and moved [Tokenizers](https://github.com/ankane/tokenizers-ruby) to it and really enjoyed using it.
>
> Thanks for creating this!

Thanks! I’m happy it proving useful and you’re having a good time working with it.

Those gems both look cool, and potentially stuff I’ll have actual use for at work, so thank you!

I don’t have access to my computer right now, so following reply is written on my phone, sorry if the formatting is weird and the inevitable autocorrect mistakes.

Finding and adding links to references is also a huge hassle on my phone, so I’ll try and follow up with that later.

> My Rust isn’t great, so I’m not sure what’s possible, but a few ideas:
> 
> 1. Support for `&mut self` / mutability in classes without having [lots of borrows](https://github.com/ankane/polars-ruby/blob/master/ext/polars/src/series.rs)

I have taken a look at this, and this is where I’ve gotten to so far:

The underlying Ruby API is `rb_data_typed_object_wrap` this takes a pointer to the struct we want to wrap. The way we do this is to `Box` the struct to allocate it on the heap, and then call `Box::into_raw` to turn the box into a pointer we can pass to Ruby.

As part of this API call we also pass a `free` function that Ruby will call when the object wrapping our struct is garbage collected. In this function we call `Box::from_raw` with the pointer to our struct, turning it back into a box, then we drop it, reclaiming the memory.

When we want to get a reference to the wrapped struct inside an object we use the `rb_check_typeddata` api call to get that pointer back, which we can then cast to a reference. However, because you could do something like pass the same object as two separate arguments to a function with no way for the Rust type system to know that’s what’s happening we can’t cast to a mutable reference, because there’s the possibility of getting two mutable references to the same struct at the same time, and that’s would break Rust’s rules. So you’re only allowed immutable references.

You can get around this by wrapping the struct in `RefCell`, which does the borrow checks at runtime and would panic in the above case.

So `RefCell`, like `Box` will allocate the data it wraps on the heap, and has a method to get a pointer to that data (`RefCell::as_ptr`). However there’s no equivalent to `Box::from_raw`, so there’d be no way to free the memory.

So the `wrap` feature automatically boxes structs because it has to, that’s the way the Ruby api works, but it doesn’t automatically use `RefCell` because a `RefCell<T>` on its own won’t work, and a `Box<RefCell<T>>` would involve following two pointers to get to the struct, and I don’t want non-mutable cases to have to pay that performance penalty.

I don’t want this to come across as saying a nicer way to do mutable references to wrapped structs isn’t possible, but this is where I’ve got to so far in thinking it through.

> 2. Support for `MyClass` and `Vec<MyClass>` as method parameters - currently needs to be `&MyClass` (and `Vec<&MyClass>` not supported)

I think the answer to 1 will help a lot understanding what’s going on here.

`MyClass` indicates ownership of the data, which precludes anyone else owning it. `&MyClass` indicates someone else owns the data, but they are temporarily letting up borrow it. And as it’s not a mutable reference, they could also be letting someone else borrow it too.

When we give a struct to Ruby to wrap in an object we are giving Ruby ownership of that data, and we don’t get it back until Ruby garbage collects that object. And Ruby gets to choose when it does that, there’s no way to influence when that happens from the Rust side.

To take ownership of the wrapped struct we’d have to leave the Ruby object wrapping that struct ‘empty’ somehow, or tell it to invalidate all references to the object on the Ruby side, and there isn’t really a way to do that.

> `Vec<&MyClass>` not supported

I hadn’t considered `Vec<&MyClass>`. The rule is heap allocated data structures like `Vec` can’t contain Ruby objects because it makes them invisible to the Ruby GC, so they could be prematurely garbage collected. So Magnus only supports conversions to data structures that contain fully fledged Rust types. `&MyClass` is a Rust type, but borrowed from a Ruby object, so it’s a weird edge case. I think it should be allowed, but I’ll need to think it through some more before implementing it.

> 3. Support for `iter()` method on `RArray`

I think what you want exists, just under a different name.

`each` on `RArray` returns an `Enumerator` that implements the `Iterator` trait. This could probably be better documented.

Naming is hard in this library as there Ruby naming conventions fighting Ruby C API conventions fighting Rust conventions.

**Comment by ankane** [comment]
Thanks @matsadler - I really appreciate the detailed response!!

For 1 and 2, the context is really helpful in understanding the design!
For 3, great! (maybe could have both in this case?)

Thanks again for all the time and effort on this.
