### ISSUE TITLE
Make `msrv` 1.57?

### ISSUE THREAD

**Issue by ianks** [matsadler/magnus#42]
Recently, [`bindgen` bumped their minimum supported Rust version to 1.57](https://github.com/rust-lang/rust-bindgen#msrv). With this change, we are unfortunately locked out of updating the package. Which brings the question, what should `rb-sys` set at MSRV as a policy?

### OS Package Manager Versions

- Ubuntu (w/ updates) == 1.61
- Debian stretch + buster == 1.41
- Debian bullseye == 1.48
- Debian bookwork + sid == 1.63
- CentOS 8 == 1.54
- Fedora 37 == 1.64
- Fedora 35 == 1.54
- Alpine 3.17 (2021-08-11 20:04:20) == 1.52
- Alpine 3.16 (2022-05-08 03:20:43) == 1.60.0-r2

### Common crates

1.56.0 ┆ rayon, once_cell, indexmap, rayon-core, hashbrowns
1.57.0 ┆ bindgen

## My general feeling ATM

The best way to distribute Rust gems is to ship precompiled binaries. This avoids the need for installing a Rust toolchain on the deployment machine and makes shipping code faster and more reliable. Most (if not all?) magnus gems I know of are using this strategy.

On top of that, `rb-sys` will (by default) install a Rust toolchain if none is found on the machine when building a gem. This allows us to keep a clean build environment and clean up any artifacts when we're done to avoid cache and image bloat.

With all of this in mind, I think supporting 1.57 is a reasonable choice for now. WDYT?

**Comment by matsadler** [comment]
So my plan was to release a 0.5 version of Magnus sometime in January, that way I can test it against the release version of Ruby 3.2 and call Ruby 3.2 officially supported. This release would have a couple of things that are technically breaking changes for semver, but should be a pretty smooth upgrade from 0.4.

Then there are a bunch of potentially disruptive breaking changes that I'm considering for 0.6, one of the things I'm thinking of would be using generic associated types in the `TryConvert` trait to fix an issue were you can get too long a lifetime out of `TryConvert` for a wrapped struct. GATs landed in Rust 1.65, so if that ends up working that'd push up the MSRV for Magnus quite a bit.

I'd like to do the 0.5 release with the same 1.51 MSRV, and treat that release as a kind of 'long term support' release, as it's probably going to be a hassle for people to upgrade to 0.6, and unreasonable to ask people to do so for bug fixes.

Were you planning to bump rb-sys to 0.10 (or even 1.0) with the MSRV change? It'd be convenient if Magnus 0.5 could depend on rb-sys 0.9, and Magnus 0.6 would bump it up to 0.10(/1.0).

**Comment by ianks** [comment]
> I'd like to do the 0.5 release with the same 1.51 MSRV

My real concern with that would be that we'd be unable to integrate any bugfixes from bindgen in the 3.2 lifecycle if they were to come up. With magnus starting to gain a lot of traction, that could cause some real pain for small benefit. 


[Compatibility for 1.51 is already low and dropping](https://lib.rs/stats), so the number of users that benefit from 1.51 support seems low, whereas the number of users would be negatively impacted by being locked to an old beindgen seems high.

### Popular magnus projects and their **minmum possible** msrv (didn't try to compile)

- wasmtime-rb = 1.56.0
- commonmarker = 1.60.0
- yrb = 1.56.0
- internal-project-1 = 1.61.0
- internal-project-2 = 1.56.0
- internal-project-1 = 1.60.0

Couldn't find any that relied on 1.51, if you do please chime in!

## On upgrading to magnus 0.6

> It'd be convenient if Magnus 0.5 could depend on rb-sys 0.9

> Then there are a bunch of potentially disruptive breaking changes that I'm considering for 0.6

i.e. I think it could cause a much larger disruption if both magnus 0.6 had a ton of breaking changes **and** rb-sys did as well. If the `rb-sys` portion of the upgrade were more stable, I imagine it would make the upgrade path more tenable?

## Proposal-ish

All in all, I think the risk-hedge benefits we gain from bindgen updates outweigh the number of users who benefit from 1.51 support. Plus it would help me sleep better at night.

so would something like the below work???

magnus 0.4 -> rb-sys 0.9 -> msrv 1.51
magnus 0.5 -> rb-sys 0.10 -> msrv 1.57 (to have breathing room for bindgen)
magnus 0.6 -> rb-sys 1.0 -> msrv 1.57 (ideally very minimal breaking changes)

**Comment by matsadler** [comment]
> [Compatibility for 1.51 is already low and dropping](https://lib.rs/stats)...
 
[semi off topic]
That's a cool graph, I hadn't seen that before. I wonder what's the number at which a Rust release stops being viable because you're almost guaranteed to hit at least one incompatible dependency?

> ### Popular magnus projects and their **minmum possible** msrv (didn't try to compile)
> ...
> Couldn't find any that relied on 1.51, if you do please chime in!

Possibly I'm over indexing on the hypothetical where someone is stuck having to use the invariably old Rust version from their distribution's package manager.

My own `halton` gem (which to be honest, is nothing more than a tech demo, I'm surprised it has any downloads) will build under 1.51, but even I'm thinking of using a 1.58 feature next time I do some work on it.

I guess what I like about being conservative on the MSRV is it gives the users of Magnus the choice, whereas being aggressive on MSRV takes away that choice. But then what's the point of giving people a choice (of using 1.51) that they'll never actually take?

Also YJIT in Ruby 3.2 needs Rust >= 1.58 (I had thought it was 1.52 but just checked), so it seems fair to assume users of Ruby would gravitate to at least that version.

> so would something like the below work???
> 
> magnus 0.4 -> rb-sys 0.9 -> msrv 1.51 magnus 0.5 -> rb-sys 0.10 -> msrv 1.57 (to have breathing room for bindgen) magnus 0.6 -> rb-sys 1.0 -> msrv 1.57 (ideally very minimal breaking changes)

Yeah, that seems reasonable.

I might bump the MSRV of Magnus 0.6 to MSRV 1.65 if GATs work out like I hope and I feel like the benefit is worth it, but that wouldn't really have any bearing on rb-sys 1.0 sticking with MSRV 1.57 if you're happy there.

**Comment by matsadler** [comment]
The next version of Magnus (0.6) will increase the MSRV to (at least) 1.61.
