### ISSUE TITLE
Please consider updating rb-sys dependency to >= v0.9.57

### ISSUE THREAD

**Issue by marvinthepa** [matsadler/magnus#52]
So that I can benefit from https://github.com/oxidize-rb/rb-sys/pull/134` :smiley:

**Comment by marvinthepa** [comment]
Sorry, this might be a non-issue due to my limited understanding of Cargo.

Feel free to close if you think that this is not necessary.

**Comment by matsadler** [comment]
No worries, it's not immediately clear with the way Cargo handles specifying versions, but when you have a dependency in Cargo.toml like:

``` toml
rb-sys = "0.9.56"
```

This actually means ">=0.9.56, <0.10"

The docs are at: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

So if you create a new project with Magnus right now, you'll get `rb-sys` 0.9.58.

``` sh
~> cd src/
~/src> cargo new --lib example
     Created library `example` package
~/src> cd example/
~/s/example> cargo add magnus
    Updating crates.io index
      Adding magnus v0.4.4 to dependencies.
             Features:
             - embed
             - rb-sys-interop
             - ruby-static
~/s/example> cargo tree
example v0.1.0 (/Users/mat/src/example)
└── magnus v0.4.4
    ├── magnus-macros v0.3.0 (proc-macro)
    │   └── ...
    └── rb-sys v0.9.58
```

If you've got a pre-existing project then running `cargo update --package rb-sys` should upgrade you (though I usually just `cargo update` to update everything, due to the Rust community strictly following semver it basically never breaks stuff).

**Comment by marvinthepa** [comment]
Thanks for taking the time to write this very detailed and friendly explanation.

The rust community has the reputation of being a very welcoming place, and you, @matsadler, are absolutely living up to that reputation. :heart:

**Comment by masukomi** [comment]
because helpful maintainer responses are worth calling out, I'm going to second everything @marvinthepa  said. Thank you :D
