### ISSUE TITLE
Possibility for `Result<Vec<T>, Error>` ?

### ISSUE THREAD

**Issue by gjtorikian** [matsadler/magnus#66]
I'm running into a strange issue when trying to return a `Result<Vec<TypedData>, Error>` from a Rust function

```
   Compiling what_you_say v1.0.0 (/Users/gjtorikian/Development/yettoapp/what_you_say/ext/what_you_say)
error[E0277]: the trait bound `Result<Vec<WhatYouSayLang>, magnus::Error>: method::private::ReturnValue` is not satisfied
    --> ext/what_you_say/src/lib.rs:156:43
     |
156  |     c_lang.define_singleton_method("all", function!(WhatYouSayLang::all, 0))?;
     |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `method::private::ReturnValue` is not implemented for `Result<Vec<WhatYouSayLang>, magnus::Error>`
     |
     = help: the following other types implement trait `method::private::ReturnValue`:
               Result<T, magnus::Error>
               Result<Yield<I>, magnus::Error>
               Result<YieldSplat<I>, magnus::Error>
               Result<YieldValues<I>, magnus::Error>
     = note: required for `Result<Vec<WhatYouSayLang>, magnus::Error>` to implement `ReturnValue`
note: required by a bound in `Function0::<Func, Res>::new`
    --> /Users/gjtorikian/.cargo/registry/src/github.com-1ecc6299db9ec823/magnus-0.5.1/src/method.rs:3153:10
     |
3153 |     Res: ReturnValue,
     |          ^^^^^^^^^^^ required by this bound in `Function0::<Func, Res>::new`
     = note: this error originates in the macro `function` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: the method `call_handle_error` exists for struct `Function0<fn() -> Result<Vec<WhatYouSayLang>, magnus::Error> {WhatYouSayLang::all}, Result<Vec<WhatYouSayLang>, magnus::Error>>`, but its trait bounds were not satisfied
   --> ext/what_you_say/src/lib.rs:156:43
    |
156 |     c_lang.define_singleton_method("all", function!(WhatYouSayLang::all, 0))?;
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method cannot be called on `Function0<fn() -> Result<Vec<WhatYouSayLang>, magnus::Error> {WhatYouSayLang::all}, Result<Vec<WhatYouSayLang>, magnus::Error>>` due to unsatisfied trait bounds
    |
   ::: /Users/gjtorikian/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:504:1
    |
504 | pub enum Result<T, E> {
    | --------------------- doesn't satisfy `_: ReturnValue`
    |
    = note: the following trait bounds were not satisfied:
            `Result<Vec<WhatYouSayLang>, magnus::Error>: ReturnValue`
    = note: this error originates in the macro `function` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `what_you_say` due to 2 previous errors
```

I am guessing it's due to [this trait](https://github.com/matsadler/magnus/blob/2b13647adb6d395aacd6d15f1a3fbebbd6890fec/src/method.rs#L262). Would it be possible to implement this for a vector of types as well?

**Comment by matsadler** [comment]
I think implementing `IntoValueFromNative` for the type you're returning should get this working for you. This is an `unsafe` trait as it should only be implemented for types that are not / do not contain Ruby values. Implementing it would looks something like:

``` rust
// this is safe as WhatYouSayLang does not contain any Ruby types
unsafe impl magnus::IntoValueFromNative for WhatYouSayLang {}
```

This isn't automatically implemented for types implementing `TypedData` (which is what the `#[wrap]` macro does) because whether or not a type contains a Ruby value isn't something the type system can know.

---

So the error message kind of sucks, what's happening is `ReturnValue` is implemented for `T` and `Result<T, Error>` where `T` implements `IntoValue`. `Vec<T>` only implements `IntoValue` when `T` implements `IntoValueFromNative`, because it's [not safe to put Ruby values in a Vec](https://docs.rs/magnus/0.5.1/magnus/#safety). So what we want is it to say `WhatYouSayLang` doesn't satisfy `IntoValueFromNative`, but unfortunately we get the mess you see. I think there is work being done in Rust to allow crates to customise messages like this, so I'll adopt that when it becomes available for cases like this.

---

I might be able to make this automatic in a future version. I've generally tried to do as much with types and traits, using macros to cover the last few gaps. Hence the default `impl<T: TypedData > IntoValue for T`, but I might remove that and instead have the `#[wrap]` macro generate an impl of `IntoValue` just for the wrapped type. The macro would be able to determine if the type contains a Ruby value or not (you have to specify `mark` in the macro if it does), so would be able to automatically implement `IntoValueFromNative` when it can.

**Comment by gjtorikian** [comment]
Thanks very much for the explanation! The `unsafe impl` did work, and it did remind me that I've used `unsafe impl Send` in other similar situations when dealing with the GVL (unrelated to this specific problem, but perhaps another area where documentation would help).
