### ISSUE TITLE
How to keep Rust object reference for related Ruby object

### ISSUE THREAD

**Issue by aharpervc** [matsadler/magnus#70]
I have some Rust code I'd like to expose to Ruby, so I've set up a test project using magnus. I'd like to create an instance of a Rust object in a Rust function, and then re-use that instance in other Rust methods exposed to Ruby.

This is similar to your Point example from the readme: https://github.com/matsadler/magnus#wrapping-rust-types-in-ruby-objects

However, the difference is that I don't want this entire object serialized for Ruby access. Therefore I'm not using the magnus::wrap attribute from your example, and I get the corresponding `the trait bound TypedData is not satisfied` as expected in that case.

Do you have a recommendation for how to do this? Is there a way to exclude individual struct properties from type wrapping so that Rust references stay in Rust? Does this make sense?

**Comment by matsadler** [comment]
I'm not sure I quite follow. I'm not sure if the disconnect is me not understanding your question, or you not quite understanding what Magnus is doing with the `#[wrap]` attribute macro (sorry, docs could be better).

If it's me missing something a bit of example code might help. Even if it won't compile, just what you'd like to be able to write.

Here's some more details on what is happening with `#[wrap]` that'll hopefully make things clearer if they aren't already:

Wrap does not serialise Rust types to Ruby. When Rust data with the `#[wrap]` attribute is returned to Ruby it gives ownership of that Rust data over to Ruby, it's otherwise unchanged. When you later get a reference it's a reference to that original data.

Here's the Point example from the readme with some of the automatic type conversions done manually, maybe this will make it clear what's going on?

``` rust
use magnus::{
    class, define_class, method, prelude::*, typed_data::Obj, Error, Integer, IntoValue,
    TryConvert, Value,
};

#[magnus::wrap(class = "Point")]
struct Point {
    x: isize,
    y: isize,
}

impl Point {
    // Method that will be bound to Ruby, takes self (self is passed
    // explicitly, and will be the class new is called on) and two arguments,
    // returns a value or raises.
    // Value is the Rust name for Ruby's internal VALUE type, this is
    // essentially a pointer to a Ruby object.
    fn new(_rb_self: Value, x: Value, y: Value) -> Result<Value, Error> {
        // convert first arg to a Rust isize, erroring if it's not compatible
        let x = isize::try_convert(x)?;
        // convert second arg to a Rust isize, erroring if it's not compatible
        let y = isize::try_convert(y)?;
        // create a new Rust Point on the stack
        let point = Self { x, y };
        // give Ruby ownership of the point. This will move Point to the heap,
        // and create a Ruby object to hold a pointer to the point on the heap.
        let point_obj = Obj::<Point>::wrap(point);
        // Downcast Obj to Value (Obj is just a wrapper of a Value that's known
        // to hold a pointer to Point).
        Ok(point_obj.into_value())
    }

    // Method that will be bound to Ruby, taking only self, and returning a
    // value or raising.
    fn x(rb_self: Value) -> Result<Value, Error> {
        // check the value we got really is an object with a pointer to a Point
        let self_obj = <Obj<Point>>::try_convert(rb_self)?;
        // get a reference to the original Point returned from new
        let self_ref = self_obj.get();
        // get the x field from that reference, as an isize
        let val = self_ref.x;
        // convert that to a Ruby integer
        let int = Integer::from_i64(val as i64);
        // Downcast Integer to Value (Integer is just a wrapper of a Value 
        // that's known be an instance of Ruby's Integer class).
        Ok(int.into_value())
    }
}

#[magnus::init]
fn init() -> Result<(), Error> {
    // create/get the Ruby Point class
    let class = define_class("Point", class::object())?;
    // define a new class method (note this example uses the method! macro
    // which passes self, not the function! macro that skips self), binding the
    // rust function to Ruby
    class.define_singleton_method("new", method!(Point::new, 2))?;
    // bind an instance method
    class.define_method("x", method!(Point::x, 0))?;
    Ok(())
}
```

It's not possible to take back ownership of the data from Ruby, as that would potentially leave the Ruby object that had a pointer to that data with an invalid pointer, you can only ever get a reference.

If you really need to you could do something like:

``` rust
struct Point {
    x: isize,
    y: isize,
}

#[magnus::wrap(class = "Point")]
struct MaybePoint(RefCell<Option<Point>>);

impl MaybePoint {
    fn new(x: isize, y: isize) -> Self {
        MaybePoint(RefCell::new(Some(Point { x, y })))
    }

    // can be used from Rust code to take back `Point` from a `&MaybePoint` reference,
    // leaving `None` in its place
    fn take(&self) -> Option<Point> {
        self.0.borrow_mut().take()
    }

    // all methods that will be exposed to Ruby get real awkward as they have to check
    // if there is or isn't an inner `Point`
    fn x(&self) -> Result<isize, Error> {
        match *self.0.borrow() {
            Some(point) => Ok(point.x),
            None => Err(Error::new(exception::runtime_error(), "empty point")),
        }
    }

    // ... and so on
}
```

**Comment by aharpervc** [comment]
> I'm not sure I quite follow. I'm not sure if the disconnect is me not understanding your question, or you not quite understanding what Magnus is doing with the #[wrap] attribute macr

Mostly me not understanding... I am fairly new to Rust and it's difficult to figure out how to ask the right question.

> Wrap does not serialise Rust types to Ruby. When Rust data with the `#[wrap]` attribute is returned to Ruby it gives ownership of that Rust data over to Ruby, it's otherwise unchanged. When you later get a reference it's a reference to that original data.

This helps a lot, I was thinking wrap was doing serialization on the struct.

> If it's me missing something a bit of example code might help. Even if it won't compile, just what you'd like to be able to write.

Yes, I have modified your Point code with the basic situation I'm trying to understand.

```rust
use magnus::{function, method, prelude::*, Error};

struct Point {
    x: isize,
    y: isize,
    // note: *don't* want to copy this value; should only be one reference
    layers: Option<Vec<u8>>,
}

#[magnus::wrap(class = "Point")]
struct MutPoint(std::cell::RefCell<Point>);

impl MutPoint {
    fn new() -> Self {
        Self {
            0: RefCell::new(Point {
                x: 0,
                y: 0,
                layers: None,
            })
        }
    }

    fn set_x(&self, i: isize) {
        self.0.borrow_mut().x = i;
    }

    fn get_x(&self) -> isize {
        self.0.borrow().x
    }
    
    // method available to Ruby
    fn process(&self) -> usize {
        // difficulty: how to borrow from inside the option?
        match &self.0.borrow_mut().layers {
            Some(mut x) => {
                add_layer(&mut x);
                x.len()
            },
            None => 0,
        }
    }
}

// simulating an existing api; this function not directly exposed to Ruby
fn add_layer(x: &mut Vec<u8>) {
    x.push(1);
}


#[magnus::init]
fn init() -> Result<(), Error> {
    let p_class = magnus::define_class("Point", magnus::class::object())?;
    p_class.define_singleton_method("new", function!(MutPoint::new, 0))?;
    p_class.define_method("set_x", method!(MutPoint::set_x, 1))?;
    p_class.define_method("get_x", method!(MutPoint::get_x, 0))?;
    p_class.define_method("process", method!(MutPoint::process, 0))?;

    Ok(())
}
```

This is slightly different than your example, being a RefCell of a Point with an Option, vs a RefCell of an Option of a Point.

**Comment by matsadler** [comment]
I *think* your question is just a general Rust question, rather than something specific to Magnus.

If you need the `Option` like your example (say your real case the thing in the `Option` isn't a `Vec` with a natural empty state) I think you should be able to use [`Option::as_mut`](https://doc.rust-lang.org/stable/std/option/enum.Option.html#method.as_mut) Here's a Rust playground with an example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fc3d43a580cc231bf8f213c99c861e13

I'm not really sure from your example how you'd progress from the `None` to `Some` state. One way you could do that with [`Option::get_or_insert_with`](https://doc.rust-lang.org/stable/std/option/enum.Option.html#method.get_or_insert_with) looks like: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=18b7d602e09daf9e870f3782d6227e99

If you're using a `Vec` I'd suggest skipping the `Option` and just using an empty `Vec` for the none state. That'd look like: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=64084405e34cf4718b6298d18b0ff29d

**Comment by aharpervc** [comment]
Thank you, that is very helpful! I'll work on figuring out how to adapt your examples to my scenario.

My original project was to see if I could expose some async Rust logic to Ruby as normal methods. I was going to turn them into blocking functions with Tokio, but then I didn't want the Tokio runtime reference to be serialized to Ruby. I was also hoping to define it as an option, so it'd be a None until the Ruby -> Rust method was called, then the Option would be filled in just in time, then used by wrapping the original logic (eg, passed as a method parameter to enable block_on). There's other stateful properties on the top level refcell struct too, which adds complication. There's probably a way to do this, but I'll have to think more about patterns for borrowing multiple properties from a refcell like that.

Regardless, at this point I agree it isn't about magnus' behavior any more, so I'll close this issue.
