### ISSUE TITLE
TryConvertOwned is private; how to implement TryConvert for custom Rust structs containing collections?

### ISSUE THREAD

**Issue by Qqwy** [matsadler/magnus#78]
Given the following Rust structs:

```
use magnus::{prelude::*, Error, TryConvert};

struct Topic {
  title: String,
  posts: Vec<Post>,
}

struct Post {
  body: String,
  author_id: usize,
}

impl TryConvert for Post {
    fn try_convert(val: magnus::Value) -> Result<Self, Error> {
        val.respond_to("body", false)?;
        val.respond_to("author_id", false)?;

        let body = val.funcall("body", ())?;
        let author_id = val.funcall("author_id", ())?;
        Ok(Post{body, author_id})
    }
}

impl TryConvert for Topic {
    fn try_convert(val: magnus::Value) -> Result<Self, Error> {
        val.respond_to("title", false)?;
        val.respond_to("posts", false)?;

        let title : String = val.funcall("title", ())?;
        let posts : Vec<Post> = val.funcall("posts", ())?; # <- Compiler complains here
        Ok(Title{title, posts})
    }
}

```

it is possible to implement `TryConvert` for `Post` as seen above.
But impossible to implement it for `Topic`, as `Vec<Post>` only implements it if `Post` implements `TryConvertOwned`, resulting in a compiler error.

However, that trait is private within Magnus (to be precise, the `try_convert` module which contains it is private). 

Should this trait maybe be made public?
Or am I 'holding it wrong'?

**Comment by matsadler** [comment]
This was an oversight on my part.

I've pushed a change to the [0.5 current release branch](https://github.com/matsadler/magnus/tree/0.5) that makes `try_convert` public, you should be able to use that [via a git dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories). I will do a release with this change, but I'm currently on holiday and my time is otherwise occupied, so it might take a week or so until I can do that.

**Comment by matsadler** [comment]
I've put out a 0.5.4 release with the fix for this.

I also (as I missed saying it in my last message) wanted to say thank you for reporting this issue, and thank you for the nice clear example, it really helped.
